import json
from datetime import UTC, datetime, timedelta

from sqlalchemy import or_, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.analysis.schemas import AnalysisMetadata, RiskScoreBreakdown
from app.core.config import get_int_env
from app.db.models import AlertRecord
from app.models.alert import MitreTechnique, SecurityAlert
from app.models.alert_update import AlertStatusUpdate

AGGREGATION_WINDOW_SECONDS = get_int_env("ALERT_AGGREGATION_WINDOW_SECONDS", 300)


class AlertRepository:
    """
    Persist and query security alerts from the relational database.

    Parameters:
     session - SQLAlchemy database session

    Returns:
     Repository for alert persistence and status updates

    Raises:
     None
    """

    def __init__(self, session: Session) -> None:
        """
        Initialize repository with a database session.

        Parameters:
         session - SQLAlchemy database session

        Returns:
         None

        Raises:
         None
        """

        self.session = session

    def save(self, alert: SecurityAlert) -> SecurityAlert:
        """
        Insert or update one security alert.

        Parameters:
         alert - security alert generated by the analysis pipeline

        Returns:
         Persisted security alert

        Raises:
         None
        """

        event_time = self._alert_event_time(alert)
        record = self._get_record(alert.alert_id) or self._get_record_by_event_id(alert.event_id)
        is_exact_event_update = record is not None

        if record is None:
            record = self._get_recent_aggregate(alert, event_time)

        if record is None:
            record = AlertRecord(alert_id=alert.alert_id, event_id=alert.event_id)
            self.session.add(record)

        self._apply_alert(
            record,
            alert,
            event_time=event_time,
            increment_event_count=not is_exact_event_update,
        )

        try:
            self.session.commit()
        except IntegrityError:
            self.session.rollback()
            record = self._get_record(alert.alert_id) or self._get_record_by_event_id(alert.event_id)

            if record is None:
                raise

            self._apply_alert(
                record,
                alert,
                event_time=event_time,
                increment_event_count=False,
            )
            self.session.commit()

        self.session.refresh(record)
        return self._to_alert(record)

    def list_recent(
        self,
        count: int = 20,
        status: str | None = None,
        risk_level: str | None = None,
        requires_human_review: bool | None = None,
    ) -> list[SecurityAlert]:
        """
        List recent alerts with optional workflow filters.

        Parameters:
         count - maximum number of alerts to return
         status - optional alert workflow status filter
         risk_level - optional alert risk level filter
         requires_human_review - optional human review filter

        Returns:
         Recent security alerts ordered by update time descending

        Raises:
         None
        """

        statement = select(AlertRecord)

        if status:
            statement = statement.where(AlertRecord.status == status)

        if risk_level:
            statement = statement.where(AlertRecord.risk_level == risk_level)

        if requires_human_review is not None:
            statement = statement.where(
                AlertRecord.requires_human_review == requires_human_review
            )

        statement = statement.order_by(AlertRecord.updated_at.desc()).limit(count * 3)
        records = self.session.scalars(statement).all()
        return [self._to_alert(record) for record in self._deduplicate_records(records)[:count]]

    def get_by_alert_id(self, alert_id: str) -> SecurityAlert | None:
        """
        Return one alert by alert ID.

        Parameters:
         alert_id - unique alert identifier

        Returns:
         Security alert when found, otherwise None

        Raises:
         None
        """

        record = self._get_record(alert_id)

        if record is None:
            return None

        return self._to_alert(record)

    def update_status(
        self,
        alert_id: str,
        update: AlertStatusUpdate,
    ) -> SecurityAlert | None:
        """
        Update workflow status and analyst fields for one alert.

        Parameters:
         alert_id - unique alert identifier
         update - requested status update

        Returns:
         Updated alert when found, otherwise None

        Raises:
         None
        """

        record = self._get_record(alert_id)

        if record is None:
            return None

        now = datetime.utcnow()
        record.status = update.status
        record.analyst_note = update.analyst_note
        record.handled_by = update.handled_by
        record.handled_at = now
        record.updated_at = now

        if update.status in {"investigating", "needs_review"}:
            record.requires_human_review = True

        if update.status in {"resolved", "false_positive", "auto_triaged"}:
            record.requires_human_review = False

        self.session.commit()
        self.session.refresh(record)
        return self._to_alert(record)

    def _get_record(self, alert_id: str) -> AlertRecord | None:
        """
        Return one database record by alert ID.

        Parameters:
         alert_id - unique alert identifier

        Returns:
         Alert record when found, otherwise None

        Raises:
         None
        """

        statement = select(AlertRecord).where(AlertRecord.alert_id == alert_id)
        return self.session.scalars(statement).first()

    def _deduplicate_records(self, records: list[AlertRecord]) -> list[AlertRecord]:
        """
        Keep one alert record per source event ID for list views.

        Parameters:
         records - alert records ordered from newest to oldest

        Returns:
         Deduplicated records preserving newest-first order

        Raises:
         None
        """

        seen_event_ids: set[str] = set()
        deduplicated: list[AlertRecord] = []

        for record in records:
            if record.event_id in seen_event_ids:
                continue

            seen_event_ids.add(record.event_id)
            deduplicated.append(record)

        return deduplicated

    def _get_record_by_event_id(self, event_id: str) -> AlertRecord | None:
        """
        Return one database record by source event ID.

        Parameters:
         event_id - source security event identifier

        Returns:
         Alert record when found, otherwise None

        Raises:
         None
        """

        statement = (
            select(AlertRecord)
            .where(
                or_(
                    AlertRecord.event_id == event_id,
                    AlertRecord.event_ids_json.like(f'%"{event_id}"%'),
                )
            )
            .order_by(AlertRecord.updated_at.desc())
        )
        return self.session.scalars(statement).first()

    def _get_recent_aggregate(
        self,
        alert: SecurityAlert,
        event_time: datetime,
    ) -> AlertRecord | None:
        """
        Return a recent aggregate record for the same alert category.

        Parameters:
         alert - incoming security alert
         event_time - normalized event time used for window matching

        Returns:
         Existing aggregate alert when found, otherwise None

        Raises:
         None
        """

        aggregation_key = self._aggregation_key(alert)
        window_start = event_time - timedelta(seconds=AGGREGATION_WINDOW_SECONDS)
        statement = (
            select(AlertRecord)
            .where(AlertRecord.aggregation_key == aggregation_key)
            .where(AlertRecord.last_seen >= window_start)
            .order_by(AlertRecord.last_seen.desc(), AlertRecord.updated_at.desc())
        )
        return self.session.scalars(statement).first()

    def _apply_alert(
        self,
        record: AlertRecord,
        alert: SecurityAlert,
        event_time: datetime | None = None,
        increment_event_count: bool = True,
    ) -> None:
        """
        Copy SecurityAlert fields onto a database record.

        Parameters:
         record - database record to update
         alert - security alert source object
         event_time - normalized event time used for aggregate fields
         increment_event_count - whether this save represents a new event in the aggregate

        Returns:
         None

        Raises:
         None
        """

        record.event_id = alert.event_id
        record.event_ids_json = self._json(
            self._merge_event_ids(record.event_ids_json, alert)
        )
        record.session_id = alert.session_id
        record.aggregation_key = self._aggregation_key(alert)

        if event_time is None:
            event_time = self._alert_event_time(alert)

        if alert.event_timestamp:
            record.event_timestamp = event_time

        record.first_seen = self._min_datetime(record.first_seen, event_time)
        record.last_seen = self._max_datetime(record.last_seen, event_time)
        record.event_count = self._next_event_count(
            record,
            alert,
            increment_event_count,
        )

        record.attack_type = alert.attack_type
        record.risk_score = self._merged_risk_score(
            record,
            alert,
            increment_event_count,
        )
        record.risk_level = self._level(record.risk_score)
        record.source_ip = alert.source_ip
        record.target = alert.target
        record.confidence = alert.confidence
        record.evidence_json = self._json(alert.evidence)
        record.mitre_attack_json = self._json(
            [item.model_dump(mode="json") for item in alert.mitre_attack]
        )
        record.recommendations_json = self._json(alert.recommendations)
        record.report_markdown = alert.report_markdown
        record.analysis_mode = alert.analysis_mode
        record.score_breakdown_json = self._optional_json(alert.score_breakdown)
        record.analysis_metadata_json = self._optional_json(alert.analysis_metadata)
        record.status = self._merged_status(record, alert, increment_event_count)
        record.automation_decision = self._merged_automation_decision(
            record,
            alert,
            increment_event_count,
        )
        record.triage_reason = alert.triage_reason
        record.requires_human_review = (
            record.requires_human_review or alert.requires_human_review
            if increment_event_count
            else alert.requires_human_review
        )
        record.business_owner = alert.business_owner
        record.asset_name = alert.asset_name
        record.asset_criticality = alert.asset_criticality
        record.context_references_json = self._json(alert.context_references)
        record.analyst_note = alert.analyst_note
        record.handled_by = alert.handled_by
        record.llm_used = alert.llm_used
        record.llm_skipped_reason = alert.llm_skipped_reason
        record.llm_summary = alert.llm_summary
        record.llm_model = alert.llm_model
        record.llm_provider = alert.llm_provider
        record.llm_latency_ms = alert.llm_latency_ms
        record.llm_prompt_tokens = alert.llm_prompt_tokens
        record.llm_completion_tokens = alert.llm_completion_tokens
        record.llm_total_tokens = alert.llm_total_tokens
        record.llm_error = alert.llm_error

        if alert.handled_at:
            record.handled_at = datetime.fromisoformat(alert.handled_at)

        record.updated_at = datetime.utcnow()

    def _to_alert(self, record: AlertRecord) -> SecurityAlert:
        """
        Convert a database record into a SecurityAlert.

        Parameters:
         record - database alert record

        Returns:
         Security alert reconstructed from persistent storage

        Raises:
         None
        """

        score_breakdown = self._load_optional_model(
            record.score_breakdown_json,
            RiskScoreBreakdown,
        )
        analysis_metadata = self._load_optional_model(
            record.analysis_metadata_json,
            AnalysisMetadata,
        )
        mitre_attack = [
            MitreTechnique.model_validate(item)
            for item in self._load_json(record.mitre_attack_json, [])
        ]

        return SecurityAlert(
            alert_id=record.alert_id,
            session_id=record.session_id,
            event_id=record.event_id,
            event_ids=self._load_json(record.event_ids_json, []),
            event_timestamp=self._format_utc_timestamp(
                record.event_timestamp or record.created_at
            ),
            first_seen=self._format_utc_timestamp(
                record.first_seen or record.event_timestamp or record.created_at
            ),
            last_seen=self._format_utc_timestamp(
                record.last_seen or record.event_timestamp or record.updated_at
            ),
            event_count=record.event_count or 1,
            attack_type=record.attack_type,
            risk_score=record.risk_score,
            risk_level=record.risk_level,
            source_ip=record.source_ip,
            target=record.target,
            confidence=record.confidence,
            evidence=self._load_json(record.evidence_json, []),
            mitre_attack=mitre_attack,
            recommendations=self._load_json(record.recommendations_json, []),
            report_markdown=record.report_markdown,
            analysis_mode=record.analysis_mode,
            score_breakdown=score_breakdown,
            analysis_metadata=analysis_metadata,
            status=record.status,
            automation_decision=record.automation_decision,
            triage_reason=record.triage_reason,
            requires_human_review=record.requires_human_review,
            business_owner=record.business_owner,
            asset_name=record.asset_name,
            asset_criticality=record.asset_criticality,
            context_references=self._load_json(record.context_references_json, []),
            analyst_note=record.analyst_note,
            handled_by=record.handled_by,
            handled_at=record.handled_at.isoformat() if record.handled_at else None,
            llm_used=record.llm_used,
            llm_skipped_reason=record.llm_skipped_reason,
            llm_summary=record.llm_summary,
            llm_model=record.llm_model,
            llm_provider=record.llm_provider,
            llm_latency_ms=record.llm_latency_ms,
            llm_prompt_tokens=record.llm_prompt_tokens,
            llm_completion_tokens=record.llm_completion_tokens,
            llm_total_tokens=record.llm_total_tokens,
            llm_error=record.llm_error,
        )

    def _json(self, value: object) -> str:
        """
        Serialize a Python value to JSON text.

        Parameters:
         value - value to serialize

        Returns:
         JSON string

        Raises:
         None
        """

        return json.dumps(value, ensure_ascii=False)

    def _optional_json(self, value: object | None) -> str | None:
        """
        Serialize an optional Pydantic model or value to JSON text.

        Parameters:
         value - optional value to serialize

        Returns:
         JSON string or None

        Raises:
         None
        """

        if value is None:
            return None

        if hasattr(value, "model_dump"):
            return self._json(value.model_dump(mode="json"))

        return self._json(value)

    def _load_json(self, raw: str | None, fallback: object) -> object:
        """
        Deserialize JSON text with a fallback value.

        Parameters:
         raw - JSON string to deserialize
         fallback - fallback value used when raw is empty

        Returns:
         Deserialized JSON value

        Raises:
         None
        """

        if not raw:
            return fallback

        return json.loads(raw)

    def _merge_event_ids(self, raw: str | None, alert: SecurityAlert) -> list[str]:
        """
        Merge event IDs already stored on an aggregate with an incoming alert.

        Parameters:
         raw - JSON list of event IDs stored on the database record
         alert - incoming security alert

        Returns:
         Ordered unique event IDs represented by the aggregate

        Raises:
         None
        """

        merged: list[str] = []

        for event_id in [*self._load_json(raw, []), *alert.event_ids, alert.event_id]:
            if event_id and event_id not in merged:
                merged.append(event_id)

        return merged

    def _next_event_count(
        self,
        record: AlertRecord,
        alert: SecurityAlert,
        increment_event_count: bool,
    ) -> int:
        """
        Calculate aggregate event count for a saved alert.

        Parameters:
         record - database alert record being updated
         alert - incoming security alert
         increment_event_count - whether this save represents a new event in the aggregate

        Returns:
         Updated aggregate event count

        Raises:
         None
        """

        current_count = record.event_count or 0
        incoming_count = alert.event_count or 1

        if current_count <= 0:
            return max(incoming_count, 1)

        if not increment_event_count:
            return max(current_count, incoming_count)

        return max(current_count + 1, incoming_count)

    def _aggregation_key(self, alert: SecurityAlert) -> str:
        """
        Build the key used to merge repeated alert traffic.

        Parameters:
         alert - security alert to group

        Returns:
         Stable aggregation key for source, target, and attack type

        Raises:
         None
        """

        return "|".join(
            [
                alert.source_ip.strip().lower(),
                alert.target.strip().lower(),
                alert.attack_type.strip().lower(),
            ]
        )

    def _merged_risk_score(
        self,
        record: AlertRecord,
        alert: SecurityAlert,
        increment_event_count: bool,
    ) -> int:
        """
        Calculate the risk score to store on an alert or aggregate.

        Parameters:
         record - database alert record being updated
         alert - incoming security alert
         increment_event_count - whether this save represents a new event in the aggregate

        Returns:
         Incoming score for exact updates, or the highest score for aggregate updates

        Raises:
         None
        """

        if not increment_event_count:
            return alert.risk_score

        current_score = getattr(record, "risk_score", None)

        if current_score is None:
            return alert.risk_score

        return max(current_score, alert.risk_score)

    def _level(self, score: int) -> str:
        """
        Convert a risk score into a risk level.

        Parameters:
         score - risk score from 0 to 100

        Returns:
         Risk level string

        Raises:
         None
        """

        if score >= 90:
            return "critical"
        if score >= 70:
            return "high"
        if score >= 40:
            return "medium"
        return "low"

    def _merged_status(
        self,
        record: AlertRecord,
        alert: SecurityAlert,
        increment_event_count: bool,
    ) -> str:
        """
        Calculate the workflow status to store on an alert or aggregate.

        Parameters:
         record - database alert record being updated
         alert - incoming security alert
         increment_event_count - whether this save represents a new event in the aggregate

        Returns:
         Incoming status for exact updates, or the higher-priority status for aggregate updates

        Raises:
         None
        """

        if not increment_event_count:
            return alert.status

        priority = {
            "false_positive": 0,
            "resolved": 1,
            "auto_triaged": 2,
            "investigating": 3,
            "needs_review": 4,
        }
        current_status = record.status or alert.status

        if priority.get(alert.status, 0) >= priority.get(current_status, 0):
            return alert.status

        return current_status

    def _merged_automation_decision(
        self,
        record: AlertRecord,
        alert: SecurityAlert,
        increment_event_count: bool,
    ) -> str:
        """
        Calculate the automation decision to store on an alert or aggregate.

        Parameters:
         record - database alert record being updated
         alert - incoming security alert
         increment_event_count - whether this save represents a new event in the aggregate

        Returns:
         Incoming decision for exact updates, or the higher-priority decision for aggregate updates

        Raises:
         None
        """

        if not increment_event_count:
            return alert.automation_decision

        priority = {
            "observe_only": 0,
            "auto_close": 1,
            "notify_owner": 2,
            "block_ip_recommended": 3,
            "human_review_required": 4,
        }
        current_decision = record.automation_decision or alert.automation_decision

        if priority.get(alert.automation_decision, 0) >= priority.get(current_decision, 0):
            return alert.automation_decision

        return current_decision

    def _alert_event_time(self, alert: SecurityAlert) -> datetime:
        """
        Return a UTC-naive event time for one alert.

        Parameters:
         alert - security alert containing optional event timestamp fields

        Returns:
         UTC-naive event datetime

        Raises:
         None
        """

        raw_time = alert.event_timestamp or alert.last_seen or alert.first_seen

        if raw_time:
            return self._to_utc_naive(raw_time)

        return datetime.now(UTC).replace(tzinfo=None)

    def _min_datetime(
        self,
        current: datetime | None,
        candidate: datetime,
    ) -> datetime:
        """
        Return the earlier of two optional datetimes.

        Parameters:
         current - existing datetime value
         candidate - candidate datetime value

        Returns:
         Earlier datetime

        Raises:
         None
        """

        if current is None:
            return candidate

        return min(current, candidate)

    def _max_datetime(
        self,
        current: datetime | None,
        candidate: datetime,
    ) -> datetime:
        """
        Return the later of two optional datetimes.

        Parameters:
         current - existing datetime value
         candidate - candidate datetime value

        Returns:
         Later datetime

        Raises:
         None
        """

        if current is None:
            return candidate

        return max(current, candidate)

    def _load_optional_model(self, raw: str | None, model_class):
        """
        Deserialize optional JSON text into a Pydantic model.

        Parameters:
         raw - JSON string to deserialize
         model_class - Pydantic model class used for validation

        Returns:
         Pydantic model instance or None

        Raises:
         None
        """

        if not raw:
            return None

        return model_class.model_validate(json.loads(raw))

    def _to_utc_naive(self, value: str) -> datetime:
        """
        Convert an ISO timestamp to a UTC datetime suitable for SQLite storage.

        Parameters:
         value - ISO timestamp string from a security alert

        Returns:
         UTC datetime without timezone info for consistent SQLite storage

        Raises:
         ValueError - raised when the timestamp cannot be parsed
        """

        parsed = datetime.fromisoformat(value)

        if parsed.tzinfo is None:
            return parsed

        return parsed.astimezone(UTC).replace(tzinfo=None)

    def _format_utc_timestamp(self, value: datetime) -> str:
        """
        Format a database datetime as an explicit UTC ISO timestamp.

        Parameters:
         value - database datetime value

        Returns:
         ISO timestamp string with UTC timezone

        Raises:
         None
        """

        if value.tzinfo is None:
            value = value.replace(tzinfo=UTC)
        else:
            value = value.astimezone(UTC)

        return value.isoformat()
