import json
from datetime import datetime

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.analysis.schemas import AnalysisMetadata, RiskScoreBreakdown
from app.db.models import AlertRecord
from app.models.alert import MitreTechnique, SecurityAlert
from app.models.alert_update import AlertStatusUpdate


class AlertRepository:
    """
    Persist and query security alerts from the relational database.

    Parameters:
     session - SQLAlchemy database session

    Returns:
     Repository for alert persistence and status updates

    Raises:
     None
    """

    def __init__(self, session: Session) -> None:
        """
        Initialize repository with a database session.

        Parameters:
         session - SQLAlchemy database session

        Returns:
         None

        Raises:
         None
        """

        self.session = session

    def save(self, alert: SecurityAlert) -> SecurityAlert:
        """
        Insert or update one security alert.

        Parameters:
         alert - security alert generated by the analysis pipeline

        Returns:
         Persisted security alert

        Raises:
         None
        """

        record = self._get_record(alert.alert_id)

        if record is None:
            record = AlertRecord(alert_id=alert.alert_id, event_id=alert.event_id)
            self.session.add(record)

        self._apply_alert(record, alert)
        self.session.commit()
        self.session.refresh(record)
        return self._to_alert(record)

    def list_recent(
        self,
        count: int = 20,
        status: str | None = None,
        requires_human_review: bool | None = None,
    ) -> list[SecurityAlert]:
        """
        List recent alerts with optional workflow filters.

        Parameters:
         count - maximum number of alerts to return
         status - optional alert workflow status filter
         requires_human_review - optional human review filter

        Returns:
         Recent security alerts ordered by update time descending

        Raises:
         None
        """

        statement = select(AlertRecord)

        if status:
            statement = statement.where(AlertRecord.status == status)

        if requires_human_review is not None:
            statement = statement.where(
                AlertRecord.requires_human_review == requires_human_review
            )

        statement = statement.order_by(AlertRecord.updated_at.desc()).limit(count)
        records = self.session.scalars(statement).all()
        return [self._to_alert(record) for record in records]

    def get_by_alert_id(self, alert_id: str) -> SecurityAlert | None:
        """
        Return one alert by alert ID.

        Parameters:
         alert_id - unique alert identifier

        Returns:
         Security alert when found, otherwise None

        Raises:
         None
        """

        record = self._get_record(alert_id)

        if record is None:
            return None

        return self._to_alert(record)

    def update_status(
        self,
        alert_id: str,
        update: AlertStatusUpdate,
    ) -> SecurityAlert | None:
        """
        Update workflow status and analyst fields for one alert.

        Parameters:
         alert_id - unique alert identifier
         update - requested status update

        Returns:
         Updated alert when found, otherwise None

        Raises:
         None
        """

        record = self._get_record(alert_id)

        if record is None:
            return None

        now = datetime.utcnow()
        record.status = update.status
        record.analyst_note = update.analyst_note
        record.handled_by = update.handled_by
        record.handled_at = now
        record.updated_at = now

        if update.status in {"investigating", "needs_review"}:
            record.requires_human_review = True

        if update.status in {"resolved", "false_positive", "auto_triaged"}:
            record.requires_human_review = False

        self.session.commit()
        self.session.refresh(record)
        return self._to_alert(record)

    def _get_record(self, alert_id: str) -> AlertRecord | None:
        """
        Return one database record by alert ID.

        Parameters:
         alert_id - unique alert identifier

        Returns:
         Alert record when found, otherwise None

        Raises:
         None
        """

        statement = select(AlertRecord).where(AlertRecord.alert_id == alert_id)
        return self.session.scalars(statement).first()

    def _apply_alert(self, record: AlertRecord, alert: SecurityAlert) -> None:
        """
        Copy SecurityAlert fields onto a database record.

        Parameters:
         record - database record to update
         alert - security alert source object

        Returns:
         None

        Raises:
         None
        """

        record.event_id = alert.event_id
        record.attack_type = alert.attack_type
        record.risk_score = alert.risk_score
        record.risk_level = alert.risk_level
        record.source_ip = alert.source_ip
        record.target = alert.target
        record.confidence = alert.confidence
        record.evidence_json = self._json(alert.evidence)
        record.mitre_attack_json = self._json(
            [item.model_dump(mode="json") for item in alert.mitre_attack]
        )
        record.recommendations_json = self._json(alert.recommendations)
        record.report_markdown = alert.report_markdown
        record.analysis_mode = alert.analysis_mode
        record.score_breakdown_json = self._optional_json(alert.score_breakdown)
        record.analysis_metadata_json = self._optional_json(alert.analysis_metadata)
        record.status = alert.status
        record.automation_decision = alert.automation_decision
        record.triage_reason = alert.triage_reason
        record.requires_human_review = alert.requires_human_review
        record.business_owner = alert.business_owner
        record.asset_name = alert.asset_name
        record.asset_criticality = alert.asset_criticality
        record.context_references_json = self._json(alert.context_references)
        record.analyst_note = alert.analyst_note
        record.handled_by = alert.handled_by

        if alert.handled_at:
            record.handled_at = datetime.fromisoformat(alert.handled_at)

        record.updated_at = datetime.utcnow()

    def _to_alert(self, record: AlertRecord) -> SecurityAlert:
        """
        Convert a database record into a SecurityAlert.

        Parameters:
         record - database alert record

        Returns:
         Security alert reconstructed from persistent storage

        Raises:
         None
        """

        score_breakdown = self._load_optional_model(
            record.score_breakdown_json,
            RiskScoreBreakdown,
        )
        analysis_metadata = self._load_optional_model(
            record.analysis_metadata_json,
            AnalysisMetadata,
        )
        mitre_attack = [
            MitreTechnique.model_validate(item)
            for item in self._load_json(record.mitre_attack_json, [])
        ]

        return SecurityAlert(
            alert_id=record.alert_id,
            event_id=record.event_id,
            attack_type=record.attack_type,
            risk_score=record.risk_score,
            risk_level=record.risk_level,
            source_ip=record.source_ip,
            target=record.target,
            confidence=record.confidence,
            evidence=self._load_json(record.evidence_json, []),
            mitre_attack=mitre_attack,
            recommendations=self._load_json(record.recommendations_json, []),
            report_markdown=record.report_markdown,
            analysis_mode=record.analysis_mode,
            score_breakdown=score_breakdown,
            analysis_metadata=analysis_metadata,
            status=record.status,
            automation_decision=record.automation_decision,
            triage_reason=record.triage_reason,
            requires_human_review=record.requires_human_review,
            business_owner=record.business_owner,
            asset_name=record.asset_name,
            asset_criticality=record.asset_criticality,
            context_references=self._load_json(record.context_references_json, []),
            analyst_note=record.analyst_note,
            handled_by=record.handled_by,
            handled_at=record.handled_at.isoformat() if record.handled_at else None,
        )

    def _json(self, value: object) -> str:
        """
        Serialize a Python value to JSON text.

        Parameters:
         value - value to serialize

        Returns:
         JSON string

        Raises:
         None
        """

        return json.dumps(value, ensure_ascii=False)

    def _optional_json(self, value: object | None) -> str | None:
        """
        Serialize an optional Pydantic model or value to JSON text.

        Parameters:
         value - optional value to serialize

        Returns:
         JSON string or None

        Raises:
         None
        """

        if value is None:
            return None

        if hasattr(value, "model_dump"):
            return self._json(value.model_dump(mode="json"))

        return self._json(value)

    def _load_json(self, raw: str | None, fallback: object) -> object:
        """
        Deserialize JSON text with a fallback value.

        Parameters:
         raw - JSON string to deserialize
         fallback - fallback value used when raw is empty

        Returns:
         Deserialized JSON value

        Raises:
         None
        """

        if not raw:
            return fallback

        return json.loads(raw)

    def _load_optional_model(self, raw: str | None, model_class):
        """
        Deserialize optional JSON text into a Pydantic model.

        Parameters:
         raw - JSON string to deserialize
         model_class - Pydantic model class used for validation

        Returns:
         Pydantic model instance or None

        Raises:
         None
        """

        if not raw:
            return None

        return model_class.model_validate(json.loads(raw))
