import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
BACKEND_DIR = ROOT_DIR / "backend"
sys.path.append(str(BACKEND_DIR))

from app.analysis.followup import AnalysisFollowupMessage
from app.analysis.state import AnalysisState
from app.llm.followup_answerer import AnalysisFollowupAnswerer
from app.llm.schemas import LLMConfig, LLMFollowupResult
from app.models.alert import SecurityAlert
from app.models.event import SecurityEvent


class FakeFollowupClient:
    """
    Return deterministic follow-up answers for tests.

    Parameters:
     result - deterministic result returned from answer_followup

    Returns:
     Fake follow-up LLM client

    Raises:
     None
    """

    def __init__(self, result: LLMFollowupResult) -> None:
        """
        Initialize fake client state.

        Parameters:
         result - deterministic result returned from answer_followup

        Returns:
         None

        Raises:
         None
        """

        self.result = result
        self.called = False
        self.messages: list[dict[str, str]] = []

    def answer_followup(self, messages: list[dict[str, str]]) -> LLMFollowupResult:
        """
        Return the configured result and record prompt messages.

        Parameters:
         messages - prompt messages generated by the answerer

        Returns:
         Deterministic follow-up result

        Raises:
         None
        """

        self.called = True
        self.messages = messages
        return self.result


def build_state() -> AnalysisState:
    """
    Build deterministic analysis state for follow-up tests.

    Parameters:
     None

    Returns:
     Analysis state containing final alert context

    Raises:
     None
    """

    state = AnalysisState(
        session_id="session-followup-test",
        event=SecurityEvent(
            source_ip="45.67.89.10",
            path="/login",
            url="/login?id=1",
        ),
    )
    state.final_alert = SecurityAlert(
        alert_id="alert-followup-test",
        session_id=state.session_id,
        event_id="event-followup-test",
        attack_type="SQL Injection",
        risk_score=92,
        risk_level="critical",
        source_ip="45.67.89.10",
        target="/login",
        confidence=0.9,
        evidence=["WAF rule 942100 matched"],
        recommendations=["Check parameterized queries"],
    )
    state.add_finding(
        finding_type="attack_detection",
        title="Detected SQL Injection",
        evidence=["WAF rule 942100 matched"],
        confidence=0.9,
        source="decision_agent",
    )
    return state


def test_followup_answerer_skips_when_llm_disabled() -> None:
    """
    Verify disabled LLM config returns an explicit skipped response.

    Parameters:
     None

    Returns:
     None

    Raises:
     None
    """

    client = FakeFollowupClient(LLMFollowupResult(used=True))
    answerer = AnalysisFollowupAnswerer(
        config=LLMConfig(enabled=False, api_key="key", base_url="http://llm"),
        client=client,
    )

    response = answerer.answer(
        build_state(),
        "为什么是 critical？",
        [
            AnalysisFollowupMessage(role="user", content="先解释一下证据"),
            AnalysisFollowupMessage(role="assistant", content="主要证据是 WAF 942100"),
        ],
    )

    assert client.called is False
    assert response.llm_used is False
    assert response.llm_error == "LLM_DISABLED"
    assert "LLM_DISABLED" in response.answer_markdown


def test_followup_answerer_answers_with_saved_context() -> None:
    """
    Verify enabled LLM config answers using saved analysis context.

    Parameters:
     None

    Returns:
     None

    Raises:
     None
    """

    client = FakeFollowupClient(
        LLMFollowupResult(
            used=True,
            answer_markdown="因为命中了 SQL 注入规则且风险分为 92。",
            model="qwen3-max",
            provider="dashscope",
            latency_ms=88.0,
            total_tokens=120,
        )
    )
    answerer = AnalysisFollowupAnswerer(
        config=LLMConfig(
            enabled=True,
            api_key="key",
            base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
            provider="dashscope",
            model="qwen3-max",
        ),
        client=client,
    )

    response = answerer.answer(
        build_state(),
        "为什么是 critical？",
        [
            AnalysisFollowupMessage(role="user", content="先解释一下证据"),
            AnalysisFollowupMessage(role="assistant", content="主要证据是 WAF 942100"),
        ],
    )

    assert client.called is True
    assert "session-followup-test" in client.messages[1]["content"]
    assert "SQL Injection" in client.messages[1]["content"]
    assert "先解释一下证据" in client.messages[1]["content"]
    assert "主要证据是 WAF 942100" in client.messages[1]["content"]
    assert response.llm_used is True
    assert response.answer_markdown == "因为命中了 SQL 注入规则且风险分为 92。"
    assert response.llm_total_tokens == 120
