import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
BACKEND_DIR = ROOT_DIR / "backend"
sys.path.append(str(BACKEND_DIR))

from app.agents.orchestrator import SecurityAnalysisOrchestrator
from app.llm.schemas import LLMAttackClassificationResult
from app.memory.long_term_schemas import LongTermMemoryWriteResult
from app.memory.schemas import IpMemorySummary
from app.models.alert import SecurityAlert
from app.models.event import ParsedSecurityEvent
from app.models.event import SecurityEvent


class InMemoryEventMemory:
    """
    Provide deterministic event memory for orchestrator tests.

    Parameters:
     None

    Returns:
     In-memory replacement for EventMemory

    Raises:
     None
    """

    def __init__(self) -> None:
        """
        Initialize the in-memory alert counter.

        Parameters:
         None

        Returns:
         None

        Raises:
         None
        """

        self.count = 0
        self.attack_types: set[str] = set()
        self.targets: set[str] = set()

    def get_ip_summary(self, source_ip: str) -> IpMemorySummary:
        """
        Return current in-memory summary for a source IP.

        Parameters:
         source_ip - source IP address

        Returns:
         In-memory source IP summary

        Raises:
         None
        """

        return IpMemorySummary(
            source_ip=source_ip,
            alert_count=self.count,
            attack_types=sorted(self.attack_types),
            targets=sorted(self.targets),
            storage_available=True,
        )

    def record_alert(self, alert) -> None:
        """
        Record one alert in memory.

        Parameters:
         alert - generated security alert

        Returns:
         None

        Raises:
         None
        """

        self.count += 1
        self.attack_types.add(alert.attack_type)
        self.targets.add(alert.target)

    def enrich_alert(self, alert, summary: IpMemorySummary):
        """
        Delegate memory enrichment to the real EventMemory implementation.

        Parameters:
         alert - generated security alert
         summary - source IP summary

        Returns:
         Security alert enriched with memory context

        Raises:
         None
        """

        from app.memory.event_memory import EventMemory

        return EventMemory().enrich_alert(alert, summary)


class NoopLLMUnknownClassifier:
    """
    Skip LLM unknown classification during context orchestration tests.

    Parameters:
     None

    Returns:
     Test unknown classifier replacement

    Raises:
     None
    """

    def enhance(
        self,
        parsed: ParsedSecurityEvent,
    ) -> tuple[ParsedSecurityEvent, LLMAttackClassificationResult]:
        """
        Return the parsed event unchanged.

        Parameters:
         parsed - parsed security event before LLM fallback

        Returns:
         Unchanged parsed event and skipped classification result

        Raises:
         None
        """

        return parsed, LLMAttackClassificationResult(skipped_reason="RULE_CLASSIFIED")


class NoopLLMReportEnhancer:
    """
    Skip LLM report enhancement during context orchestration tests.

    Parameters:
     None

    Returns:
     Test LLM report enhancer replacement

    Raises:
     None
    """

    def enhance(self, alert: SecurityAlert) -> SecurityAlert:
        """
        Return the alert with deterministic skipped LLM metadata.

        Parameters:
         alert - alert before report enhancement

        Returns:
         Alert with LLM disabled metadata

        Raises:
         None
        """

        return alert.model_copy(
            update={
                "llm_used": False,
                "llm_skipped_reason": "LLM_DISABLED",
                "llm_model": "fake-model",
                "llm_provider": "fake-provider",
            }
        )


class NoopSessionMemoryStore:
    """
    Skip Redis session memory writes during context orchestration tests.

    Parameters:
     None

    Returns:
     Test session memory replacement

    Raises:
     None
    """

    def save_state(self, state) -> bool:
        """
        Pretend the analysis state was saved.

        Parameters:
         state - analysis state generated by the orchestrator

        Returns:
         True

        Raises:
         None
        """

        return True


class NoopLongTermMemoryStore:
    """
    Skip Milvus long-term memory writes during context orchestration tests.

    Parameters:
     None

    Returns:
     Test long-term memory replacement

    Raises:
     None
    """

    def save_analysis(self, alert: SecurityAlert, state) -> LongTermMemoryWriteResult:
        """
        Pretend long-term memory is disabled.

        Parameters:
         alert - final security alert
         state - analysis state generated by the orchestrator

        Returns:
         Skipped long-term memory write result

        Raises:
         None
        """

        return LongTermMemoryWriteResult(skipped_reason="TEST_DISABLED")

    def search_for_alert(self, alert: SecurityAlert, state, top_k: int = 3):
        """
        Pretend similar long-term memory search is disabled.

        Parameters:
         alert - final security alert
         state - analysis state generated by the orchestrator
         top_k - maximum result count

        Returns:
         Empty result list and deterministic skipped reason

        Raises:
         None
        """

        return [], "TEST_DISABLED"


def test_orchestrator_adds_rag_intel_memory_and_judgment() -> None:
    """
    Verify orchestrator enriches alerts with RAG, threat intelligence, memory, and judgment.

    Parameters:
     None

    Returns:
     None

    Raises:
     None
    """

    orchestrator = SecurityAnalysisOrchestrator()
    orchestrator.event_memory = InMemoryEventMemory()
    orchestrator.llm_unknown_classifier = NoopLLMUnknownClassifier()
    orchestrator.llm_report_enhancer = NoopLLMReportEnhancer()
    orchestrator.session_memory = NoopSessionMemoryStore()
    orchestrator.long_term_memory = NoopLongTermMemoryStore()

    event = SecurityEvent(
        source_ip="45.67.89.10",
        url="/login?id=1' OR '1'='1",
        path="/login",
        query="id=1' OR '1'='1",
        user_agent="sqlmap/1.7",
        waf_rule_id="942100",
        waf_message="SQL Injection Attack Detected",
    )

    alert = orchestrator.analyze(event)
    text = "\n".join(alert.evidence) + "\n" + (alert.report_markdown or "")

    assert alert.attack_type == "SQL Injection"
    assert "attack_patterns.md" in text or "owasp_crs.md" in text
    assert "local_mock" in text
    assert "Memory" in text
    assert "45.67.89.10" in text
