import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
BACKEND_DIR = ROOT_DIR / "backend"
sys.path.append(str(BACKEND_DIR))

from app.llm.schemas import LLMAttackClassificationResult, LLMConfig
from app.llm.unknown_attack_classifier import LLMUnknownAttackClassifier
from app.models.event import ParsedSecurityEvent, SecurityEvent


class FakeClassificationClient:
    """
    Return deterministic LLM classification results for tests.

    Parameters:
     result - deterministic result returned from classify_attack

    Returns:
     Fake classification client

    Raises:
     None
    """

    def __init__(self, result: LLMAttackClassificationResult) -> None:
        """
        Initialize fake client state.

        Parameters:
         result - deterministic result returned from classify_attack

        Returns:
         None

        Raises:
         None
        """

        self.result = result
        self.called = False
        self.messages: list[dict[str, str]] = []

    def classify_attack(
        self,
        messages: list[dict[str, str]],
    ) -> LLMAttackClassificationResult:
        """
        Return the configured result and record prompt messages.

        Parameters:
         messages - prompt messages generated by the classifier

        Returns:
         Deterministic LLM classification result

        Raises:
         None
        """

        self.called = True
        self.messages = messages
        return self.result


def build_parsed(attack_type: str = "Unknown") -> ParsedSecurityEvent:
    """
    Build a deterministic parsed event for classifier tests.

    Parameters:
     attack_type - initial attack type assigned by rule parsing

    Returns:
     Parsed security event ready for LLM fallback classification

    Raises:
     None
    """

    event = SecurityEvent(
        source_ip="6.6.6.6",
        method="GET",
        url="/fetch?url=http://169.254.169.254/latest/meta-data/",
        path="/fetch",
        query="url=http://169.254.169.254/latest/meta-data/",
        status=403,
        user_agent="Mozilla/5.0",
        raw_log="GET /fetch?url=http://169.254.169.254/latest/meta-data/",
    )

    return ParsedSecurityEvent(
        event=event,
        attack_type=attack_type,
        evidence=[],
        confidence=0.2,
    )


def build_config(enabled: bool = True) -> LLMConfig:
    """
    Build deterministic LLM config for classifier tests.

    Parameters:
     enabled - whether LLM is enabled

    Returns:
     LLM configuration ready for tests

    Raises:
     None
    """

    return LLMConfig(
        enabled=enabled,
        unknown_classifier_enabled=True,
        api_key="key",
        base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        provider="dashscope",
        model="qwen3-max",
        unknown_classifier_min_confidence=0.7,
    )


def test_unknown_classifier_skips_when_rule_already_classified() -> None:
    """
    Verify LLM fallback does not call the model for rule-classified events.

    Parameters:
     None

    Returns:
     None

    Raises:
     None
    """

    client = FakeClassificationClient(LLMAttackClassificationResult(used=True))
    classifier = LLMUnknownAttackClassifier(config=build_config(), client=client)

    parsed, result = classifier.enhance(build_parsed(attack_type="SQL Injection"))

    assert client.called is False
    assert parsed.attack_type == "SQL Injection"
    assert result.skipped_reason == "RULE_CLASSIFIED"


def test_unknown_classifier_accepts_high_confidence_attack_type() -> None:
    """
    Verify LLM fallback can replace Unknown with a supported high-confidence type.

    Parameters:
     None

    Returns:
     None

    Raises:
     None
    """

    client = FakeClassificationClient(
        LLMAttackClassificationResult(
            used=True,
            attack_suspected=True,
            attack_type="SSRF",
            confidence=0.92,
            reason="Request targets cloud metadata IP.",
            matched_indicators=["169.254.169.254", "url parameter controls destination"],
        )
    )
    classifier = LLMUnknownAttackClassifier(config=build_config(), client=client)

    parsed, result = classifier.enhance(build_parsed())

    assert client.called is True
    assert "169.254.169.254" in client.messages[1]["content"]
    assert result.used is True
    assert parsed.attack_type == "SSRF"
    assert parsed.confidence == 0.92
    assert "LLM Unknown Classification" in parsed.attack_features
    assert any("LLM Unknown 补充识别：SSRF" in item for item in parsed.evidence)


def test_unknown_classifier_rejects_low_confidence_result() -> None:
    """
    Verify low-confidence LLM fallback results do not replace Unknown.

    Parameters:
     None

    Returns:
     None

    Raises:
     None
    """

    client = FakeClassificationClient(
        LLMAttackClassificationResult(
            used=True,
            attack_suspected=True,
            attack_type="SSRF",
            confidence=0.41,
        )
    )
    classifier = LLMUnknownAttackClassifier(config=build_config(), client=client)

    parsed, result = classifier.enhance(build_parsed())

    assert result.used is True
    assert parsed.attack_type == "Unknown"
    assert any("低于阈值" in item for item in parsed.evidence)


def test_unknown_classifier_records_failure_without_breaking_parsed_event() -> None:
    """
    Verify LLM fallback errors preserve Unknown and append evidence.

    Parameters:
     None

    Returns:
     None

    Raises:
     None
    """

    client = FakeClassificationClient(
        LLMAttackClassificationResult(
            used=False,
            error="TIMEOUT",
            model="qwen3-max",
            provider="dashscope",
        )
    )
    classifier = LLMUnknownAttackClassifier(config=build_config(), client=client)

    parsed, result = classifier.enhance(build_parsed())

    assert client.called is True
    assert result.error == "TIMEOUT"
    assert parsed.attack_type == "Unknown"
    assert "LLM Unknown 补充识别失败：TIMEOUT" in parsed.evidence
