import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
BACKEND_DIR = ROOT_DIR / "backend"
sys.path.append(str(BACKEND_DIR))

from app.llm.report_enhancer import LLMReportEnhancer
from app.llm.schemas import LLMConfig, LLMReportResult
from app.models.alert import SecurityAlert


class FakeLLMClient:
    """
    Return deterministic LLM report results for tests.

    Parameters:
     result - deterministic result returned from generate_report

    Returns:
     Fake LLM client

    Raises:
     None
    """

    def __init__(self, result: LLMReportResult) -> None:
        """
        Initialize fake client state.

        Parameters:
         result - deterministic result returned from generate_report

        Returns:
         None

        Raises:
         None
        """

        self.result = result
        self.called = False
        self.messages: list[dict[str, str]] = []

    def generate_report(self, messages: list[dict[str, str]]) -> LLMReportResult:
        """
        Return the configured result and record prompt messages.

        Parameters:
         messages - prompt messages generated by the enhancer

        Returns:
         Deterministic LLM report result

        Raises:
         None
        """

        self.called = True
        self.messages = messages
        return self.result


def build_alert(
    risk_level: str = "critical",
    requires_review: bool = True,
) -> SecurityAlert:
    """
    Build a deterministic alert for LLM tests.

    Parameters:
     risk_level - risk level assigned to the alert
     requires_review - whether the alert requires human review

    Returns:
     Security alert ready for LLM enhancement

    Raises:
     None
    """

    return SecurityAlert(
        alert_id="alert-llm-test",
        event_id="event-llm-test",
        attack_type="SQL Injection",
        risk_score=95,
        risk_level=risk_level,
        source_ip="45.67.89.10",
        target="/login",
        confidence=0.92,
        evidence=["命中 SQL 注入特征", "WAF 已拦截请求"],
        recommendations=["检查参数化查询", "回溯源 IP 历史行为"],
        report_markdown="## 原始报告",
        status="needs_review",
        automation_decision="human_review_required",
        triage_reason="critical asset requires review",
        requires_human_review=requires_review,
    )


def test_llm_report_enhancer_skips_when_disabled() -> None:
    """
    Verify disabled LLM configuration does not call the client.

    Parameters:
     None

    Returns:
     None

    Raises:
     None
    """

    client = FakeLLMClient(LLMReportResult(used=True))
    enhancer = LLMReportEnhancer(
        config=LLMConfig(enabled=False, api_key="key", base_url="http://llm"),
        client=client,
    )

    alert = enhancer.enhance(build_alert())

    assert client.called is False
    assert alert.llm_used is False
    assert alert.llm_skipped_reason == "LLM_DISABLED"


def test_llm_report_enhancer_generates_report_with_fake_client() -> None:
    """
    Verify enabled LLM configuration appends generated report metadata.

    Parameters:
     None

    Returns:
     None

    Raises:
     None
    """

    client = FakeLLMClient(
        LLMReportResult(
            used=True,
            summary="该请求疑似 SQL 注入攻击，WAF 已拦截。",
            report_markdown="### 事件概览\n\n检测到 SQL 注入尝试。",
            model="qwen3-max",
            provider="dashscope",
            latency_ms=123.0,
            prompt_tokens=100,
            completion_tokens=50,
            total_tokens=150,
        )
    )
    enhancer = LLMReportEnhancer(
        config=LLMConfig(
            enabled=True,
            api_key="key",
            base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
            provider="dashscope",
            model="qwen3-max",
        ),
        client=client,
    )

    alert = enhancer.enhance(build_alert())

    assert client.called is True
    assert "SQL Injection" in client.messages[1]["content"]
    assert alert.llm_used is True
    assert alert.llm_summary == "该请求疑似 SQL 注入攻击，WAF 已拦截。"
    assert alert.llm_total_tokens == 150
    assert "LLM 分析师报告" in (alert.report_markdown or "")
    assert alert.risk_score == 95
    assert alert.attack_type == "SQL Injection"


def test_llm_report_enhancer_records_failure_without_breaking_alert() -> None:
    """
    Verify LLM errors are recorded without changing deterministic alert fields.

    Parameters:
     None

    Returns:
     None

    Raises:
     None
    """

    client = FakeLLMClient(
        LLMReportResult(
            used=False,
            error="TIMEOUT",
            model="qwen3-max",
            provider="dashscope",
            latency_ms=30000.0,
        )
    )
    enhancer = LLMReportEnhancer(
        config=LLMConfig(
            enabled=True,
            api_key="key",
            base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        ),
        client=client,
    )

    alert = enhancer.enhance(build_alert())

    assert client.called is True
    assert alert.llm_used is False
    assert alert.llm_error == "TIMEOUT"
    assert alert.risk_level == "critical"
    assert "LLM 报告生成失败：TIMEOUT" in alert.evidence
