from app.context.context_loader import ContextLoader
from app.context.context_retriever import ContextRetriever
from app.context.schemas import ContextAnalysisResult, ContextChunk, ContextReference
from app.models.alert import SecurityAlert
from app.models.event import ParsedSecurityEvent


class ContextAgent:
    """
    Retrieve enterprise context and extract fields for auto triage.

    Parameters:
     context_loader - loader used to read local enterprise context documents

    Returns:
     A context agent that enriches alerts with asset, owner, policy, and whitelist context

    Raises:
     None
    """

    def __init__(self, context_loader: ContextLoader | None = None) -> None:
        """
        Initialize the context agent.

        Parameters:
         context_loader - loader used to read local enterprise context documents

        Returns:
         None

        Raises:
         None
        """

        self.context_loader = context_loader or ContextLoader()
        self._chunks: list[ContextChunk] | None = None
        self._retriever: ContextRetriever | None = None

    def analyze(
        self,
        alert: SecurityAlert,
        parsed: ParsedSecurityEvent,
        top_k: int = 8,
    ) -> ContextAnalysisResult:
        """
        Analyze enterprise context for one alert.

        Parameters:
         alert - security alert generated by previous analysis stages
         parsed - parsed event used to build the context query
         top_k - maximum number of context references

        Returns:
         Structured enterprise context analysis result

        Raises:
         None
        """

        query = self._query(alert, parsed)
        references = self._retriever_or_build().search(query, top_k=top_k)
        result = ContextAnalysisResult(
            query=query,
            references=references,
            business_owner=self._first_metadata(references, "business_owner"),
            asset_name=self._first_metadata(references, "asset_name"),
            asset_criticality=self._first_metadata(references, "asset_criticality"),
            is_internal_scanner=self._is_internal_scanner(alert.source_ip, references),
            waf_action=self._waf_action(parsed, references),
            change_window=self._first_metadata(references, "change_window"),
            recommended_decision=self._first_metadata(references, "automation_decision"),
        )
        return result.model_copy(update={"summary": self._summary(result)})

    def enrich_alert(
        self,
        alert: SecurityAlert,
        context: ContextAnalysisResult,
    ) -> SecurityAlert:
        """
        Enrich an alert with enterprise context fields and evidence.

        Parameters:
         alert - security alert to enrich
         context - enterprise context analysis result

        Returns:
         Security alert enriched with enterprise context

        Raises:
         None
        """

        references = [
            f"{ref.title} ({ref.source}, score={ref.score:.2f})"
            for ref in context.references
        ]
        evidence = [
            *alert.evidence,
            f"企业上下文：{context.summary}",
        ]
        report_markdown = self._append_report_section(alert.report_markdown or "", context)

        return alert.model_copy(
            update={
                "business_owner": context.business_owner,
                "asset_name": context.asset_name,
                "asset_criticality": context.asset_criticality,
                "context_references": references,
                "evidence": evidence,
                "report_markdown": report_markdown,
            }
        )

    def _chunks_or_load(self) -> list[ContextChunk]:
        """
        Return cached context chunks, loading them when needed.

        Parameters:
         None

        Returns:
         Cached or newly loaded context chunks

        Raises:
         None
        """

        if self._chunks is None:
            self._chunks = self.context_loader.load_chunks()

        return self._chunks

    def _retriever_or_build(self) -> ContextRetriever:
        """
        Return cached context retriever, building it when needed.

        Parameters:
         None

        Returns:
         Context retriever backed by loaded chunks

        Raises:
         None
        """

        if self._retriever is None:
            self._retriever = ContextRetriever(self._chunks_or_load())

        return self._retriever

    def _query(self, alert: SecurityAlert, parsed: ParsedSecurityEvent) -> str:
        """
        Build an enterprise context retrieval query.

        Parameters:
         alert - security alert generated by previous analysis stages
         parsed - parsed event used to build the context query

        Returns:
         Context retrieval query string

        Raises:
         None
        """

        event = parsed.event
        rule_prefix = (event.waf_rule_id or "")[:3]
        terms = [
            alert.source_ip,
            alert.target,
            event.path,
            event.url,
            event.waf_rule_id or "",
            rule_prefix,
            event.waf_message or "",
            alert.attack_type,
            event.user_agent,
            "owner",
            "asset",
            "waf policy",
            "scanner whitelist",
            "playbook",
        ]
        return " ".join(term for term in terms if term).strip()

    def _first_metadata(
        self,
        references: list[ContextReference],
        key: str,
    ) -> str | None:
        """
        Return the first metadata value for a key from context references.

        Parameters:
         references - matched context references
         key - metadata key to extract

        Returns:
         First metadata value or None

        Raises:
         None
        """

        for reference in references:
            value = reference.metadata.get(key)

            if value:
                return value

        return None

    def _is_internal_scanner(
        self,
        source_ip: str,
        references: list[ContextReference],
    ) -> bool:
        """
        Determine whether source IP matched scanner whitelist context.

        Parameters:
         source_ip - alert source IP
         references - matched context references

        Returns:
         True when source IP is a whitelisted scanner

        Raises:
         None
        """

        for reference in references:
            if reference.category != "scanner_whitelist":
                continue

            if reference.metadata.get("ip") == source_ip:
                return True

        return False

    def _waf_action(
        self,
        parsed: ParsedSecurityEvent,
        references: list[ContextReference],
    ) -> str | None:
        """
        Infer WAF action from context references.

        Parameters:
         parsed - parsed event containing WAF rule context
         references - matched context references

        Returns:
         WAF action or None

        Raises:
         None
        """

        rule_id = parsed.event.waf_rule_id or ""

        for reference in references:
            if reference.category != "waf_policy":
                continue

            rule_prefix = reference.metadata.get("rule_prefix", "")

            if rule_prefix and rule_id.startswith(rule_prefix):
                return reference.metadata.get("waf_action")

        return None

    def _summary(self, context: ContextAnalysisResult) -> str:
        """
        Build a concise enterprise context summary.

        Parameters:
         context - enterprise context analysis result

        Returns:
         Human-readable context summary

        Raises:
         None
        """

        parts = []

        if context.asset_name:
            parts.append(f"目标资产 {context.asset_name}")

        if context.asset_criticality:
            parts.append(f"资产等级 {context.asset_criticality}")

        if context.business_owner:
            parts.append(f"负责人 {context.business_owner}")

        if context.is_internal_scanner:
            parts.append("源 IP 命中内部扫描器白名单")

        if context.waf_action:
            parts.append(f"WAF 策略为 {context.waf_action}")

        if context.change_window and context.change_window != "none":
            parts.append(f"存在变更窗口 {context.change_window}")

        return "，".join(parts) if parts else "未检索到稳定企业上下文"

    def _append_report_section(
        self,
        report_markdown: str,
        context: ContextAnalysisResult,
    ) -> str:
        """
        Append enterprise context references to markdown report.

        Parameters:
         report_markdown - original markdown report
         context - enterprise context analysis result

        Returns:
         Markdown report enriched with enterprise context

        Raises:
         None
        """

        refs = "\n".join(
            f"- **{ref.title}**（{ref.source}，{ref.category}，score={ref.score:.2f}）：{ref.snippet}"
            for ref in context.references
        )
        return (
            f"{report_markdown.rstrip()}\n\n"
            "## 企业上下文\n\n"
            f"{context.summary}\n\n"
            "**上下文引用**\n\n"
            f"{refs or '- 暂无上下文引用'}\n"
        )
