import re
from collections import Counter

from app.models.alert import SecurityAlert
from app.models.event import ParsedSecurityEvent
from app.rag.knowledge_loader import KnowledgeLoader
from app.rag.query_rewriter import SecurityQueryRewriter
from app.rag.schemas import KnowledgeChunk, KnowledgeReference, RAGAnalysisResult


class RAGAgent:
    """
    Retrieve local security knowledge and enrich generated alerts.

    Parameters:
     knowledge_loader - loader used to read local markdown security knowledge
     query_rewriter - rewriter used to build retrieval queries from parsed events

    Returns:
     A lightweight RAG agent for local security knowledge retrieval

    Raises:
     None
    """

    def __init__(
        self,
        knowledge_loader: KnowledgeLoader | None = None,
        query_rewriter: SecurityQueryRewriter | None = None,
    ) -> None:
        """
        Initialize the RAG agent.

        Parameters:
         knowledge_loader - loader used to read local markdown security knowledge
         query_rewriter - rewriter used to build retrieval queries from parsed events

        Returns:
         None

        Raises:
         None
        """

        self.knowledge_loader = knowledge_loader or KnowledgeLoader()
        self.query_rewriter = query_rewriter or SecurityQueryRewriter()
        self._chunks: list[KnowledgeChunk] | None = None

    def analyze(self, parsed: ParsedSecurityEvent, top_k: int = 3) -> RAGAnalysisResult:
        """
        Retrieve relevant security knowledge for a parsed event.

        Parameters:
         parsed - parsed security event containing attack type and evidence
         top_k - maximum number of references returned from local knowledge

        Returns:
         RAG analysis result containing summary, references, and recommendations

        Raises:
         None
        """

        query = self.query_rewriter.rewrite(parsed)
        query_terms = self._terms(query)
        ranked = self._rank(query_terms, parsed.attack_type)
        selected_chunks = [
            chunk
            for chunk, score in ranked[:top_k]
            if score > 0
        ]
        references = [
            self._to_reference(chunk, score)
            for chunk, score in ranked[:top_k]
            if score > 0
        ]

        return RAGAnalysisResult(
            query=query,
            summary=self._summary(parsed, references),
            references=references,
            recommended_actions=self._recommended_actions(selected_chunks, references),
            matched_knowledge=[item.title for item in references],
        )

    def enrich_alert(
        self,
        alert: SecurityAlert,
        parsed: ParsedSecurityEvent,
    ) -> SecurityAlert:
        """
        Enrich a security alert with RAG references and remediation actions.

        Parameters:
         alert - base security alert generated by DecisionAgent
         parsed - parsed security event used for RAG retrieval

        Returns:
         Security alert enriched with local knowledge references

        Raises:
         None
        """

        result = self.analyze(parsed)

        if not result.references:
            return alert

        evidence = [
            *alert.evidence,
            *[
                f"知识库引用：{ref.title}（{ref.source}）"
                for ref in result.references
            ],
        ]
        recommendations = self._merge_unique(
            alert.recommendations,
            result.recommended_actions,
        )
        report_markdown = self._append_report_section(
            alert.report_markdown or "",
            result,
        )

        return alert.model_copy(
            update={
                "evidence": evidence,
                "recommendations": recommendations,
                "report_markdown": report_markdown,
            }
        )

    def _chunks_or_load(self) -> list[KnowledgeChunk]:
        """
        Return cached knowledge chunks, loading them when needed.

        Parameters:
         None

        Returns:
         Cached or newly loaded knowledge chunks

        Raises:
         None
        """

        if self._chunks is None:
            self._chunks = self.knowledge_loader.load_chunks()

        return self._chunks

    def _rank(
        self,
        query_terms: list[str],
        attack_type: str,
    ) -> list[tuple[KnowledgeChunk, float]]:
        """
        Rank knowledge chunks by lightweight term overlap score.

        Parameters:
         query_terms - normalized retrieval query terms
         attack_type - attack type used to boost directly related knowledge

        Returns:
         Ranked list of knowledge chunks with scores

        Raises:
         None
        """

        query_counter = Counter(query_terms)
        ranked: list[tuple[KnowledgeChunk, float]] = []

        for chunk in self._chunks_or_load():
            chunk_counter = Counter(chunk.keywords)
            score = 0.0

            for term, weight in query_counter.items():
                if term in chunk_counter:
                    score += weight * (1 + min(chunk_counter[term], 3))

            if query_terms and chunk.title.lower() in " ".join(query_terms):
                score += 5

            score += self._attack_boost(chunk, attack_type)
            ranked.append((chunk, score))

        return sorted(ranked, key=lambda item: item[1], reverse=True)

    def _attack_boost(
        self,
        chunk: KnowledgeChunk,
        attack_type: str,
    ) -> float:
        """
        Boost knowledge chunks that directly match the current attack type.

        Parameters:
         chunk - knowledge chunk being ranked
         attack_type - attack type detected from the event

        Returns:
         Additional ranking score for directly related knowledge

        Raises:
         None
        """

        aliases = {
            "SQL Injection": ["sql injection", "942", "t1190", "sql 注入"],
            "XSS": ["xss", "941", "t1189", "cross site scripting"],
            "Path Traversal": ["path traversal", "930", "t1190", "路径穿越"],
            "Command Injection": ["command injection", "932", "t1059", "命令注入"],
            "Automated Scanner": ["automated scanner", "scanner detection", "913", "sqlmap"],
        }
        haystack = f"{chunk.title}\n{chunk.content}".lower()
        boost = 0.0

        for alias in aliases.get(attack_type, []):
            if alias.lower() in haystack:
                boost += 8

        return boost

    def _to_reference(
        self,
        chunk: KnowledgeChunk,
        score: float,
    ) -> KnowledgeReference:
        """
        Convert a knowledge chunk into a report reference.

        Parameters:
         chunk - matched knowledge chunk
         score - retrieval score assigned to the chunk

        Returns:
         Structured knowledge reference

        Raises:
         None
        """

        snippet = self._snippet(chunk.content)
        return KnowledgeReference(
            source=chunk.source,
            title=chunk.title,
            snippet=snippet,
            score=score,
        )

    def _summary(
        self,
        parsed: ParsedSecurityEvent,
        references: list[KnowledgeReference],
    ) -> str:
        """
        Build a concise RAG summary for the parsed event.

        Parameters:
         parsed - parsed security event containing attack type
         references - matched knowledge references

        Returns:
         Summary text for report enrichment

        Raises:
         None
        """

        if not references:
            return "未在本地知识库中检索到稳定匹配的安全知识。"

        titles = "、".join(ref.title for ref in references[:2])
        return f"本地知识库检索到与 {parsed.attack_type} 相关的知识条目：{titles}。"

    def _recommended_actions(
        self,
        chunks: list[KnowledgeChunk],
        references: list[KnowledgeReference],
    ) -> list[str]:
        """
        Extract remediation actions from matched knowledge references.

        Parameters:
         chunks - matched knowledge chunks used to extract remediation text
         references - matched knowledge references

        Returns:
         Deduplicated remediation action list

        Raises:
         None
        """

        actions: list[str] = []

        for chunk in chunks:
            in_remediation = False

            for line in chunk.content.splitlines():
                stripped = line.strip()

                if stripped.startswith("### 修复建议") or stripped.startswith("### 处置建议"):
                    in_remediation = True
                    continue

                if stripped.startswith("### ") and in_remediation:
                    in_remediation = False

                if not in_remediation:
                    continue

                if not stripped.startswith("- "):
                    continue

                line = stripped.removeprefix("- ").strip()

                if line:
                    actions.append(line)

        if not actions:
            for reference in references:
                actions.append(f"参考知识库条目《{reference.title}》完善检测、加固和复盘动作。")

        return self._merge_unique([], actions[:5])

    def _legacy_recommended_actions(
        self,
        references: list[KnowledgeReference],
    ) -> list[str]:
        """
        Build fallback remediation actions from reference snippets.

        Parameters:
         references - matched knowledge references

        Returns:
         Deduplicated fallback remediation action list

        Raises:
         None
        """

        actions: list[str] = []

        for reference in references:
            for line in reference.snippet.splitlines():
                line = line.strip(" -")

                if line.startswith("修复") or line.startswith("使用") or line.startswith("限制"):
                    actions.append(line)

        if actions:
            return self._merge_unique([], actions)

        return [
            f"参考知识库条目《{reference.title}》完善检测、加固和复盘动作。"
            for reference in references[:2]
        ]

    def _append_report_section(
        self,
        report_markdown: str,
        result: RAGAnalysisResult,
    ) -> str:
        """
        Append a RAG knowledge reference section to a markdown report.

        Parameters:
         report_markdown - original markdown report
         result - RAG analysis result to append

        Returns:
         Markdown report enriched with RAG references

        Raises:
         None
        """

        refs = "\n".join(
            f"- **{ref.title}**（{ref.source}）：{ref.snippet}"
            for ref in result.references
        )
        actions = "\n".join(
            f"{index}. {item}"
            for index, item in enumerate(result.recommended_actions, start=1)
        )

        return (
            f"{report_markdown.rstrip()}\n\n"
            "## RAG 知识库增强\n\n"
            f"{result.summary}\n\n"
            "**知识库引用**\n\n"
            f"{refs}\n\n"
            "**知识库补充建议**\n\n"
            f"{actions}\n"
        )

    def _snippet(self, content: str, max_length: int = 180) -> str:
        """
        Build a compact one-line snippet from markdown content.

        Parameters:
         content - markdown content used as source text
         max_length - maximum snippet length

        Returns:
         Compact snippet text

        Raises:
         None
        """

        text = re.sub(r"\s+", " ", content).strip()
        return text[:max_length]

    def _terms(self, text: str) -> list[str]:
        """
        Extract normalized retrieval terms from query text.

        Parameters:
         text - query text

        Returns:
         List of lowercase query terms

        Raises:
         None
        """

        return re.findall(r"[a-z0-9_./'-]+", text.lower())

    def _merge_unique(self, base: list[str], extra: list[str]) -> list[str]:
        """
        Merge two string lists while preserving order and removing duplicates.

        Parameters:
         base - existing string list
         extra - additional string list

        Returns:
         Deduplicated merged string list

        Raises:
         None
        """

        merged: list[str] = []
        seen: set[str] = set()

        for item in [*base, *extra]:
            if item in seen:
                continue

            seen.add(item)
            merged.append(item)

        return merged
