import re

from app.models.alert import SecurityAlert
from app.models.event import ParsedSecurityEvent
from app.rag.hybrid_retriever import HybridRetriever
from app.rag.knowledge_loader import KnowledgeLoader
from app.rag.query_rewriter import SecurityQueryRewriter
from app.rag.schemas import KnowledgeChunk, KnowledgeReference, RAGAnalysisResult, RetrievalResult


class RAGAgent:
    """
    Retrieve local security knowledge and enrich generated alerts.

    Parameters:
     knowledge_loader - loader used to read local markdown security knowledge
     query_rewriter - rewriter used to build retrieval queries from parsed events

    Returns:
     A RAG agent that uses query rewrite and hybrid retrieval for security knowledge

    Raises:
     None
    """

    def __init__(
        self,
        knowledge_loader: KnowledgeLoader | None = None,
        query_rewriter: SecurityQueryRewriter | None = None,
    ) -> None:
        """
        Initialize the RAG agent.

        Parameters:
         knowledge_loader - loader used to read local markdown security knowledge
         query_rewriter - rewriter used to build retrieval queries from parsed events

        Returns:
         None

        Raises:
         None
        """

        self.knowledge_loader = knowledge_loader or KnowledgeLoader()
        self.query_rewriter = query_rewriter or SecurityQueryRewriter()
        self._chunks: list[KnowledgeChunk] | None = None
        self._retriever: HybridRetriever | None = None

    def analyze(self, parsed: ParsedSecurityEvent, top_k: int = 4) -> RAGAnalysisResult:
        """
        Retrieve relevant security knowledge for a parsed event.

        Parameters:
         parsed - parsed security event containing attack type and evidence
         top_k - maximum number of references returned from local knowledge

        Returns:
         RAG analysis result containing summary, references, citations, and recommendations

        Raises:
         None
        """

        query = self.query_rewriter.rewrite(parsed)
        results = self._retriever_or_build().search(query, top_k=top_k)
        references = [self._to_reference(result) for result in results]
        chunks = [result.chunk for result in results]
        citations = [self._citation(reference) for reference in references]

        return RAGAnalysisResult(
            query=query,
            summary=self._summary(parsed, references),
            references=references,
            recommended_actions=self._recommended_actions(chunks, references),
            matched_knowledge=[reference.title for reference in references],
            citations=citations,
        )

    def enrich_alert(
        self,
        alert: SecurityAlert,
        parsed: ParsedSecurityEvent,
    ) -> SecurityAlert:
        """
        Enrich a security alert with RAG references and remediation actions.

        Parameters:
         alert - base security alert generated by DecisionAgent
         parsed - parsed security event used for RAG retrieval

        Returns:
         Security alert enriched with local knowledge references

        Raises:
         None
        """

        result = self.analyze(parsed)

        if not result.references:
            return alert

        evidence = [
            *alert.evidence,
            *[
                (
                    f"RAG 引用：{ref.title}（{ref.source}，"
                    f"score={ref.score:.2f}，{ref.reason}）"
                )
                for ref in result.references
            ],
        ]
        recommendations = self._merge_unique(
            alert.recommendations,
            result.recommended_actions,
        )
        report_markdown = self._append_report_section(
            alert.report_markdown or "",
            result,
        )

        return alert.model_copy(
            update={
                "evidence": evidence,
                "recommendations": recommendations,
                "report_markdown": report_markdown,
            }
        )

    def _chunks_or_load(self) -> list[KnowledgeChunk]:
        """
        Return cached knowledge chunks, loading them when needed.

        Parameters:
         None

        Returns:
         Cached or newly loaded knowledge chunks

        Raises:
         None
        """

        if self._chunks is None:
            self._chunks = self.knowledge_loader.load_chunks()

        return self._chunks

    def _retriever_or_build(self) -> HybridRetriever:
        """
        Return cached hybrid retriever, building it when needed.

        Parameters:
         None

        Returns:
         Hybrid retriever backed by loaded knowledge chunks

        Raises:
         None
        """

        if self._retriever is None:
            self._retriever = HybridRetriever(self._chunks_or_load())

        return self._retriever

    def _to_reference(self, result: RetrievalResult) -> KnowledgeReference:
        """
        Convert a retrieval result into a report reference.

        Parameters:
         result - scored retrieval result returned by HybridRetriever

        Returns:
         Structured knowledge reference

        Raises:
         None
        """

        chunk = result.chunk
        return KnowledgeReference(
            source=chunk.source,
            title=chunk.title,
            category=chunk.category,
            snippet=self._snippet(chunk.content),
            score=result.score,
            retrieval_type=result.retrieval_type,
            reason=result.reason,
        )

    def _summary(
        self,
        parsed: ParsedSecurityEvent,
        references: list[KnowledgeReference],
    ) -> str:
        """
        Build a concise RAG summary for the parsed event.

        Parameters:
         parsed - parsed security event containing attack type
         references - matched knowledge references

        Returns:
         Summary text for report enrichment

        Raises:
         None
        """

        if not references:
            return "未在本地安全知识库中检索到稳定匹配的安全知识。"

        titles = "、".join(reference.title for reference in references[:2])
        return (
            f"基于改写后的查询，知识库检索到与 {parsed.attack_type} 相关的条目："
            f"{titles}。"
        )

    def _recommended_actions(
        self,
        chunks: list[KnowledgeChunk],
        references: list[KnowledgeReference],
    ) -> list[str]:
        """
        Extract remediation actions from matched knowledge references.

        Parameters:
         chunks - matched knowledge chunks used to extract remediation text
         references - matched knowledge references

        Returns:
         Deduplicated remediation action list

        Raises:
         None
        """

        actions: list[str] = []

        for chunk in chunks:
            in_remediation = False

            for line in chunk.content.splitlines():
                stripped = line.strip()

                if stripped.startswith("### 修复建议") or stripped.startswith("### 处置建议"):
                    in_remediation = True
                    continue

                if stripped.startswith("### ") and in_remediation:
                    in_remediation = False

                if not in_remediation or not stripped.startswith("- "):
                    continue

                action = stripped.removeprefix("- ").strip()

                if action:
                    actions.append(action)

        if not actions:
            actions.extend(
                f"参考知识库条目《{reference.title}》完善检测、加固和复盘动作。"
                for reference in references[:2]
            )

        return self._merge_unique([], actions[:5])

    def _append_report_section(
        self,
        report_markdown: str,
        result: RAGAnalysisResult,
    ) -> str:
        """
        Append a RAG knowledge reference section to a markdown report.

        Parameters:
         report_markdown - original markdown report
         result - RAG analysis result to append

        Returns:
         Markdown report enriched with RAG references

        Raises:
         None
        """

        refs = "\n".join(
            (
                f"- **{ref.title}**（{ref.source}，{ref.category}，"
                f"score={ref.score:.2f}）：{ref.snippet}"
            )
            for ref in result.references
        )
        actions = "\n".join(
            f"{index}. {item}"
            for index, item in enumerate(result.recommended_actions, start=1)
        )

        return (
            f"{report_markdown.rstrip()}\n\n"
            "## RAG 知识库增强\n\n"
            f"**改写查询**：`{result.query}`\n\n"
            f"{result.summary}\n\n"
            "**知识库引用**\n\n"
            f"{refs}\n\n"
            "**知识库补充建议**\n\n"
            f"{actions}\n"
        )

    def _citation(self, reference: KnowledgeReference) -> str:
        """
        Build a compact citation string from one knowledge reference.

        Parameters:
         reference - matched knowledge reference

        Returns:
         Compact citation text

        Raises:
         None
        """

        return f"{reference.title} ({reference.source}, score={reference.score:.2f})"

    def _snippet(self, content: str, max_length: int = 180) -> str:
        """
        Build a compact one-line snippet from markdown content.

        Parameters:
         content - markdown content used as source text
         max_length - maximum snippet length

        Returns:
         Compact snippet text

        Raises:
         None
        """

        text = re.sub(r"\s+", " ", content).strip()
        return text[:max_length]

    def _merge_unique(self, base: list[str], extra: list[str]) -> list[str]:
        """
        Merge two string lists while preserving order and removing duplicates.

        Parameters:
         base - existing string list
         extra - additional string list

        Returns:
         Deduplicated merged string list

        Raises:
         None
        """

        merged: list[str] = []
        seen: set[str] = set()

        for item in [*base, *extra]:
            if item in seen:
                continue

            seen.add(item)
            merged.append(item)

        return merged
