import argparse
import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
BACKEND_DIR = ROOT_DIR / "backend"
sys.path.append(str(BACKEND_DIR))

from sqlalchemy import delete, select

from app.core.config import get_csv_env
from app.db.init_db import init_db
from app.db.models import AlertRecord
from app.db.session import SessionLocal

DEFAULT_TARGETS = ["/__waf_health"]


def list_matching_alerts(targets: list[str], limit: int = 10) -> list[AlertRecord]:
    """
    List persisted alerts whose target matches ignored health check paths.

    Parameters:
     targets - alert target paths to match
     limit - maximum number of records to return

    Returns:
     Matching alert records ordered by update time descending

    Raises:
     None
    """

    init_db()

    with SessionLocal() as session:
        statement = (
            select(AlertRecord)
            .where(AlertRecord.target.in_(targets))
            .order_by(AlertRecord.updated_at.desc())
            .limit(limit)
        )
        return list(session.scalars(statement).all())


def count_matching_alerts(targets: list[str]) -> int:
    """
    Count persisted alerts whose target matches ignored health check paths.

    Parameters:
     targets - alert target paths to match

    Returns:
     Number of matching alert records

    Raises:
     None
    """

    init_db()

    with SessionLocal() as session:
        statement = select(AlertRecord.id).where(AlertRecord.target.in_(targets))
        return len(list(session.scalars(statement).all()))


def delete_matching_alerts(targets: list[str]) -> int:
    """
    Delete persisted alerts whose target matches ignored health check paths.

    Parameters:
     targets - alert target paths to match

    Returns:
     Number of deleted alert records

    Raises:
     None
    """

    init_db()

    with SessionLocal() as session:
        statement = delete(AlertRecord).where(AlertRecord.target.in_(targets))
        result = session.execute(statement)
        session.commit()
        return int(result.rowcount or 0)


def parse_targets(raw_targets: str | None) -> list[str]:
    """
    Parse cleanup target paths from CLI or environment configuration.

    Parameters:
     raw_targets - optional comma-separated target path string

    Returns:
     List of target paths to clean

    Raises:
     None
    """

    if raw_targets:
        return [item.strip() for item in raw_targets.split(",") if item.strip()]

    return get_csv_env("WAF_COLLECTOR_IGNORED_PATHS", DEFAULT_TARGETS)


def main() -> None:
    """
    Run health check alert cleanup from the command line.

    Parameters:
     None

    Returns:
     None

    Raises:
     None
    """

    parser = argparse.ArgumentParser(
        description="Clean persisted alerts generated by WAF health check paths."
    )
    parser.add_argument(
        "--targets",
        default=None,
        help="Comma-separated alert targets to clean. Defaults to WAF_COLLECTOR_IGNORED_PATHS.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually delete matching alerts. Without this flag the script only previews.",
    )
    parser.add_argument(
        "--sample",
        type=int,
        default=10,
        help="Number of matching alerts to show in preview.",
    )
    args = parser.parse_args()

    targets = parse_targets(args.targets)
    total = count_matching_alerts(targets)
    samples = list_matching_alerts(targets, limit=args.sample)

    print(f"targets: {', '.join(targets)}")
    print(f"matching alerts: {total}")

    if samples:
        print("sample alerts:")
        for record in samples:
            print(
                f"- {record.alert_id} target={record.target} "
                f"attack_type={record.attack_type} risk={record.risk_level}/{record.risk_score}"
            )

    if not args.apply:
        print("dry run only. add --apply to delete matching alerts.")
        return

    deleted = delete_matching_alerts(targets)
    print(f"deleted alerts: {deleted}")


if __name__ == "__main__":
    main()
