from app.analysis.schemas import AnalysisMode
from app.models.alert import SecurityAlert


class AnalysisPolicy:
    """
    Select a cost-control analysis mode from the base alert risk.

    Parameters:
     None

    Returns:
     A policy object that chooses fast, enriched, or deep mode

    Raises:
     None
    """

    def select_mode(self, alert: SecurityAlert) -> AnalysisMode:
        """
        Select the analysis mode for one alert.

        Parameters:
         alert - base alert generated by the decision stage

        Returns:
         Selected analysis mode

        Raises:
         None
        """

        if alert.risk_level == "critical" or alert.risk_score >= 80:
            return "deep"

        if alert.risk_score >= 40:
            return "enriched"

        return "fast"

    def modules_for_mode(self, mode: AnalysisMode) -> tuple[list[str], list[str]]:
        """
        Return enabled and skipped modules for one analysis mode.

        Parameters:
         mode - selected analysis mode

        Returns:
         Tuple containing enabled modules and skipped modules

        Raises:
         None
        """

        all_optional = ["RAG", "ThreatIntel", "Memory"]

        if mode == "deep":
            return all_optional, []

        if mode == "enriched":
            return ["RAG", "Memory"], ["ThreatIntel"]

        return [], all_optional
