from app.analysis.schemas import RiskScoreBreakdown, RiskScoreItem
from app.models.alert import SecurityAlert


class RiskScoreBreakdownBuilder:
    """
    Build and update explainable risk score breakdowns.

    Parameters:
     None

    Returns:
     A helper for creating score breakdowns

    Raises:
     None
    """

    def from_alert(self, alert: SecurityAlert) -> RiskScoreBreakdown:
        """
        Build a score breakdown from an existing alert.

        Parameters:
         alert - alert containing score, level, confidence, and existing breakdown

        Returns:
         Risk score breakdown aligned with the alert

        Raises:
         None
        """

        if alert.score_breakdown:
            return alert.score_breakdown.model_copy(
                update={
                    "total_score": alert.risk_score,
                    "risk_level": alert.risk_level,
                    "confidence": alert.confidence,
                }
            )

        return RiskScoreBreakdown(
            base_score=0,
            items=[
                RiskScoreItem(
                    name="Base decision score",
                    score=alert.risk_score,
                    reason="Initial risk score generated by rule-based decision logic",
                    source="rule",
                )
            ],
            total_score=alert.risk_score,
            risk_level=alert.risk_level,
            confidence=alert.confidence,
        )

    def append_item(
        self,
        alert: SecurityAlert,
        name: str,
        score: int,
        reason: str,
        source: str,
    ) -> RiskScoreBreakdown:
        """
        Append one score contribution item to an alert breakdown.

        Parameters:
         alert - alert being enriched
         name - human-readable score item name
         score - risk score delta
         reason - reason for the score delta
         source - score source

        Returns:
         Updated risk score breakdown

        Raises:
         None
        """

        breakdown = self.from_alert(alert)
        return breakdown.model_copy(
            update={
                "items": [
                    *breakdown.items,
                    RiskScoreItem(
                        name=name,
                        score=score,
                        reason=reason,
                        source=source,
                    ),
                ],
                "total_score": alert.risk_score,
                "risk_level": alert.risk_level,
                "confidence": alert.confidence,
            }
        )
