from datetime import UTC, datetime
from uuid import uuid4

from pydantic import BaseModel, Field

from app.context.schemas import ContextAnalysisResult
from app.intel.schemas import ThreatIntelResult
from app.llm.schemas import LLMAttackClassificationResult
from app.memory.schemas import IpMemorySummary
from app.models.alert import SecurityAlert
from app.models.event import ParsedSecurityEvent, SecurityEvent
from app.triage.schemas import AutoTriageResult


class WorkflowStep(BaseModel):
    """
    Represent one step executed during a security analysis.

    Parameters:
     name - workflow step name
     status - execution status such as completed or skipped
     summary - concise step summary
     latency_ms - optional step latency in milliseconds

    Returns:
     Structured workflow step for session memory

    Raises:
     None
    """

    name: str
    status: str = "completed"
    summary: str = ""
    latency_ms: float | None = None


class AnalysisFinding(BaseModel):
    """
    Represent one finding produced during a security analysis.

    Parameters:
     finding_type - finding category such as attack_detection or triage
     title - concise finding title
     description - detailed finding description
     evidence - evidence supporting the finding
     confidence - confidence score from 0.0 to 1.0
     source - module that produced the finding

    Returns:
     Structured finding for session memory

    Raises:
     None
    """

    finding_type: str
    title: str
    description: str = ""
    evidence: list[str] = Field(default_factory=list)
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    source: str = ""


class AnalysisReflection(BaseModel):
    """
    Represent one post-analysis reflection or learning hint.

    Parameters:
     summary - concise reflection summary
     suggested_knowledge_update - whether knowledge base should be improved
     suggested_rule_update - whether deterministic rules should be improved
     source - module that produced the reflection

    Returns:
     Structured reflection for session memory

    Raises:
     None
    """

    summary: str
    suggested_knowledge_update: bool = False
    suggested_rule_update: bool = False
    source: str = "analysis"


class AnalysisState(BaseModel):
    """
    Store shared context produced during one security analysis.

    Parameters:
     session_id - unique analysis session identifier
     event - original normalized security event
     parsed_event - parsed event after rule and optional LLM fallback classification
     llm_unknown_classification - optional LLM fallback classification metadata
     final_alert - final alert generated by the pipeline
     context_result - enterprise context analysis result
     triage_result - automatic triage result
     threat_intel_result - threat intelligence result
     memory_summary - historical source IP memory summary
     findings - structured findings generated during analysis
     workflow_steps - workflow steps executed during analysis
     reflections - post-analysis reflections and learning hints
     created_at - ISO timestamp for state creation

    Returns:
     Analysis state used by runtime modules and session memory

    Raises:
     None
    """

    session_id: str = Field(default_factory=lambda: f"session-{uuid4().hex[:12]}")
    event: SecurityEvent
    parsed_event: ParsedSecurityEvent | None = None
    llm_unknown_classification: LLMAttackClassificationResult | None = None
    final_alert: SecurityAlert | None = None
    context_result: ContextAnalysisResult | None = None
    triage_result: AutoTriageResult | None = None
    threat_intel_result: ThreatIntelResult | None = None
    memory_summary: IpMemorySummary | None = None
    findings: list[AnalysisFinding] = Field(default_factory=list)
    workflow_steps: list[WorkflowStep] = Field(default_factory=list)
    reflections: list[AnalysisReflection] = Field(default_factory=list)
    created_at: str = Field(default_factory=lambda: datetime.now(UTC).isoformat())

    def add_workflow_step(
        self,
        name: str,
        status: str = "completed",
        summary: str = "",
        latency_ms: float | None = None,
    ) -> None:
        """
        Append one workflow step to the analysis state.

        Parameters:
         name - workflow step name
         status - execution status
         summary - concise step summary
         latency_ms - optional step latency in milliseconds

        Returns:
         None

        Raises:
         None
        """

        self.workflow_steps.append(
            WorkflowStep(
                name=name,
                status=status,
                summary=summary,
                latency_ms=latency_ms,
            )
        )

    def add_finding(
        self,
        finding_type: str,
        title: str,
        description: str = "",
        evidence: list[str] | None = None,
        confidence: float = 0.0,
        source: str = "",
    ) -> None:
        """
        Append one finding to the analysis state.

        Parameters:
         finding_type - finding category
         title - concise finding title
         description - detailed finding description
         evidence - evidence supporting the finding
         confidence - confidence score from 0.0 to 1.0
         source - module that produced the finding

        Returns:
         None

        Raises:
         None
        """

        self.findings.append(
            AnalysisFinding(
                finding_type=finding_type,
                title=title,
                description=description,
                evidence=evidence or [],
                confidence=confidence,
                source=source,
            )
        )

    def add_reflection(
        self,
        summary: str,
        suggested_knowledge_update: bool = False,
        suggested_rule_update: bool = False,
        source: str = "analysis",
    ) -> None:
        """
        Append one reflection to the analysis state.

        Parameters:
         summary - concise reflection summary
         suggested_knowledge_update - whether knowledge base should be improved
         suggested_rule_update - whether deterministic rules should be improved
         source - module that produced the reflection

        Returns:
         None

        Raises:
         None
        """

        self.reflections.append(
            AnalysisReflection(
                summary=summary,
                suggested_knowledge_update=suggested_knowledge_update,
                suggested_rule_update=suggested_rule_update,
                source=source,
            )
        )
