from app.models.alert import SecurityAlert


class LLMReportPromptBuilder:
    """
    Build a bounded prompt from structured alert analysis results.

    Parameters:
     None

    Returns:
     Prompt builder for LLM report enhancement

    Raises:
     None
    """

    def build_messages(self, alert: SecurityAlert) -> list[dict[str, str]]:
        """
        Build OpenAI-compatible chat messages for one alert.

        Parameters:
         alert - final alert generated by deterministic analysis modules

        Returns:
         Chat messages for the LLM provider

        Raises:
         None
        """

        return [
            {
                "role": "system",
                "content": self._system_prompt(),
            },
            {
                "role": "user",
                "content": self._user_prompt(alert),
            },
        ]

    def _system_prompt(self) -> str:
        """
        Build the fixed system instruction.

        Parameters:
         None

        Returns:
         System prompt text

        Raises:
         None
        """

        return (
            "你是企业 SOC 安全分析助手。你只能基于输入中的结构化告警、证据、"
            "RAG 引用、企业上下文和处置建议进行归纳，不要编造不存在的漏洞编号、"
            "IP 归属、攻击链或外部情报。请输出中文 Markdown。"
        )

    def _user_prompt(self, alert: SecurityAlert) -> str:
        """
        Build the user prompt from a security alert.

        Parameters:
         alert - final alert generated by deterministic analysis modules

        Returns:
         User prompt text

        Raises:
         None
        """

        return "\n".join(
            [
                "请基于以下安全告警生成 SOC 分析师可读报告。",
                "",
                "要求：",
                "1. 不改变 attack_type、risk_score、risk_level、confidence。",
                "2. 先给出 2-3 句话的 analyst_summary。",
                "3. 再输出 Markdown 报告，包含：事件概览、关键证据、业务影响、处置建议、需要人工确认的问题。",
                "4. 如果证据不足，要明确写出不确定性，不要补充输入中没有的信息。",
                "5. 输出必须是 JSON，格式为：{\"summary\":\"...\",\"report_markdown\":\"...\"}。",
                "",
                "告警基础信息：",
                f"- alert_id: {alert.alert_id}",
                f"- event_id: {alert.event_id}",
                f"- attack_type: {alert.attack_type}",
                f"- risk_score: {alert.risk_score}",
                f"- risk_level: {alert.risk_level}",
                f"- confidence: {alert.confidence}",
                f"- source_ip: {alert.source_ip}",
                f"- target: {alert.target}",
                f"- status: {alert.status}",
                f"- automation_decision: {alert.automation_decision}",
                f"- requires_human_review: {alert.requires_human_review}",
                "",
                "企业上下文：",
                f"- business_owner: {alert.business_owner or 'Unknown'}",
                f"- asset_name: {alert.asset_name or 'Unknown'}",
                f"- asset_criticality: {alert.asset_criticality or 'Unknown'}",
                f"- triage_reason: {alert.triage_reason or 'None'}",
                "",
                "证据：",
                self._bullet_list(alert.evidence),
                "",
                "处置建议：",
                self._numbered_list(alert.recommendations),
                "",
                "MITRE ATT&CK：",
                self._bullet_list(
                    [
                        f"{item.technique_id} {item.name}"
                        for item in alert.mitre_attack
                    ]
                ),
                "",
                "上下文引用：",
                self._bullet_list(alert.context_references),
                "",
                "当前规则/RAG报告：",
                self._truncate(alert.report_markdown or "None", 6000),
            ]
        )

    def _bullet_list(self, items: list[str]) -> str:
        """
        Format list items as Markdown bullets.

        Parameters:
         items - text items to format

        Returns:
         Markdown bullet list or None marker

        Raises:
         None
        """

        if not items:
            return "- None"

        return "\n".join(f"- {self._truncate(item, 500)}" for item in items[:20])

    def _numbered_list(self, items: list[str]) -> str:
        """
        Format list items as Markdown numbered lines.

        Parameters:
         items - text items to format

        Returns:
         Markdown numbered list or None marker

        Raises:
         None
        """

        if not items:
            return "1. None"

        return "\n".join(
            f"{index}. {self._truncate(item, 500)}"
            for index, item in enumerate(items[:20], start=1)
        )

    def _truncate(self, value: str, limit: int) -> str:
        """
        Truncate text to a maximum character count.

        Parameters:
         value - source text
         limit - maximum allowed characters

        Returns:
         Truncated text

        Raises:
         None
        """

        if len(value) <= limit:
            return value

        return f"{value[:limit]}...[truncated]"
